CXX=g++
CXXFLAGS=-I. -std=c++11 -O3
TARGET=test
SRC=main.cpp
SAMPLINGTARGET=sampling
SAMPLINGSRC=sampling.cpp
COMPARATORTARGET=comparator
COMPARATORSRC=comparator.cpp
BASELINETARGET=baseline
BASELINESOURCE=baseline.cpp

all: $(TARGET) $(COMPARATORTARGET) $(BASELINETARGET) $(SAMPLINGTARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $< -o $@

$(COMPARATORTARGET): $(COMPARATORSRC)
	$(CXX) $(CXXFLAGS) $< -o $@

$(BASELINETARGET): $(BASELINESOURCE)
	$(CXX) $(CXXFLAGS) $< -o $@

$(SAMPLINGTARGET): $(SAMPLINGSRC)
	$(CXX) $(CXXFLAGS) $< -o $@

clean:
	rm -f $(TARGET) $(COMPARATORTARGET) $(BASELINETARGET) $(SAMPLINGTARGET)